# Generated by Django 3.2 on 2021-05-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closure',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
