# Generated by Django 3.2 on 2021-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0003_auto_20210509_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bordereaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_ctr', models.CharField(max_length=20)),
                ('n_brd', models.IntegerField()),
                ('dt_clo', models.DateTimeField()),
                ('n_ord', models.IntegerField()),
                ('m_brd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dt_depot', models.DateTimeField(blank=True, null=True)),
                ('dt_jrl', models.DateTimeField(blank=True, null=True)),
                ('n_ord_jrl', models.IntegerField(blank=True, null=True)),
                ('m_jrl', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dt_pay', models.DateTimeField(blank=True, null=True)),
                ('defr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payement', models.BooleanField(default=False)),
            ],
        ),
    ]
