# Generated by Django 3.2 on 2021-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0004_bordereaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereaux',
            name='n_brd',
            field=models.IntegerField(unique=True),
        ),
    ]
