# Generated by Django 3.2 on 2021-05-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0005_alter_bordereaux_n_brd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereaux',
            name='dt_clo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bordereaux',
            name='dt_depot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bordereaux',
            name='dt_jrl',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bordereaux',
            name='dt_pay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
