# Generated by Django 3.2 on 2021-05-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0006_auto_20210510_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereaux',
            name='def_o',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
