# Generated by Django 3.2 on 2021-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0007_bordereaux_def_o'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereaux',
            name='def_o',
            field=models.IntegerField(default=0),
        ),
    ]
