# Generated by Django 3.2 on 2021-05-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0008_alter_bordereaux_def_o'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereaux',
            name='n_brd',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
