# Generated by Django 3.2 on 2021-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0010_alter_bordereaux_defr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereaux',
            name='m_jrl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
