# Generated by Django 3.2 on 2021-05-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0011_alter_bordereaux_m_jrl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closure',
            name='real_money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
