# Generated by Django 3.2 on 2021-05-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloture', '0012_alter_closure_real_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereaux',
            name='n_ord_jrl',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
