# Generated by Django 3.2 on 2021-04-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameart', models.CharField(max_length=350)),
            ],
        ),
    ]
