# Generated by Django 3.2 on 2021-05-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_cmdart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmd',
            name='med_cmded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cmdart',
            name='art_cmded',
            field=models.BooleanField(default=False),
        ),
    ]
