# Generated by Django 3.2 on 2021-05-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('p_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('params', models.TextField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('pay', models.IntegerField(default=0)),
                ('rest', models.IntegerField(default=0)),
                ('info', models.TextField(max_length=200)),
            ],
        ),
    ]
