# Generated by Django 3.2 on 2021-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labo',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
    ]
