# Generated by Django 3.2 on 2021-05-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo', '0002_alter_labo_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labo',
            name='info',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
