# Generated by Django 3.2 on 2021-05-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo', '0003_alter_labo_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labo',
            name='dt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
