# Generated by Django 3.2 on 2021-05-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labo', '0004_alter_labo_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='labo',
            name='lab_price',
            field=models.IntegerField(default=0),
        ),
    ]
