# Generated by Django 3.2.4 on 2021-06-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_commande_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='product',
            field=models.CharField(max_length=250),
        ),
    ]
